baseURL = "https://codyjames.dev"
defaultContentLanguage = "en"
enableEmoji = true
enableGitInfo = true
keywords = ["Tech", "Developer", "Linux", "JavaScript", "HTML", "Programming", "Arduino"]
languageCode = "en"
theme = "LoveIt"
title = "Cody James"
[Permalinks]
posts = ":filename"
[author]
email = "email@codyjames.dev"
link = "https://codyjames.dev/about"
name = "Cody James"
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = true
noClasses = false
[markup.tableOfContents]
endLevel = 6
startLevel = 2
[mediaTypes."text/plain"]
suffixes = ["md"]
[[menu.main]]
identifier = "posts"
name = "Posts"
post = ""
pre = ""
title = ""
url = "/posts/"
weight = 1
[[menu.main]]
identifier = "tags"
name = "Tags"
post = ""
pre = ""
title = ""
url = "/tags/"
weight = 2
[[menu.main]]
identifier = "categories"
name = "Categories"
post = ""
pre = ""
title = ""
url = "/categories/"
weight = 3
[[menu.main]]
identifier = "about"
name = "About"
title = "About Me"
url = "/about/"
weight = 4
[outputFormats.MarkDown]
isHTML = false
isPlainText = true
mediaType = "text/plain"
[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "MarkDown"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
taxonomyTerm = ["HTML"]
[params]
defaultTheme = "dark"
gitRepo = "https://github.com/codyjamestechnical/cjt-website"
version = "0.2.X"
[params.footer]
author = true
copyright = true
enabled = true
hugo = false
since = 1337
[params.header]
desktopMode = "fixed"
mobileMode = "auto"
[params.header.title]
logo = ""
name = "Cody James"
post = ""
pre = ""
typeit = false
[params.home]
rss = 10
[params.home.profile]
avatarURL = "https://codyjames.dev/images/myAvatar-smirk.svg"
enable = true
social = true
subtitle = "Web Developer, Coder, Computer Repair Tech, & Electronics Repair"
title = "Cody James"
typeit = true
[params.list]
dateFormat = "01-02"
paginate = 20
rss = 10
[params.page]
fontawesome = true
fraction = true
lightgallery = true
linkToMarkdown = true
rssFullText = true
ruby = true
twemoji = false
[params.page.code]
copy = true
maxShownLines = 10
[params.page.math]
blockLeftDelimiter = ""
blockRightDelimiter = ""
copyTex = true
enable = false
inlineLeftDelimiter = ""
inlineRightDelimiter = ""
mhchem = true
[params.page.share]
Facebook = true
HackerNews = true
Pocket = true
Reddit = true
Twitter = true
enable = true
[params.page.toc]
auto = false
enable = true
keepStatic = false
[params.search]
absoluteURL = false
contentLength = 5000
enable = true
highlightTag = "em"
maxResultLength = 20
placeholder = ""
snippetLength = 40
type = "lunr"
[params.section]
dateFormat = "01-02"
paginate = 20
rss = 10
[params.social]
Email = "email@codyjames.dev"
GitHub = "https://github.com/codyjamestechnical"
RSS = true
[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5
