backend:
  name: git-gateway
  branch: master
media_folder: "static/images"
collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true, required: false}
      - {label: "SubTitle", name: "subtitle", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Tags", name: "tags", widget: "string", required: false}
      - {label: "Featured Image", name: "featuredImage", widget: "image", required: false}
      - {label: "Hidden From Home Page", name: "hiddenFromHomePage", widget: "boolean", default: false, required: false}
      - {label: "Show Table Of Contents", name: "toc", widget: "boolean", default: false, required: false}
      - {label: "Categories", name: "categories", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
